services:
  mywebstorage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    networks:
      - ssr-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mywebstorage
    networks:
      - ssr-network

networks:
  ssr-network:
    driver: bridge
